### ISSUE TITLE
have you successfully trained your network?

### ISSUE THREAD

**Issue by lixiang-ucas** [unsky/FPN-caffe#1]
Dear unsky, have you successfully trained your network? can you provide a copy of the output caffemodel?

**Comment by unsky** [comment]
what error in your project?

**Comment by fahaihappy** [comment]
I met the error: Check failed: bottom[0]->num() == bottom[1]->num() (4 vs. 1) The data and label should have the same number.

**Comment by unsky** [comment]
@fahaihappy  i have revised the source of caffe, you must compile the FPN-CAFFE
