### ISSUE TITLE
The FPN-caffe has a poor result

### ISSUE THREAD

**Issue by chengshuai** [unsky/FPN-caffe#10]
Hi @unsky

I train the FPN-caffe in voc dataset, and the AP is 59%. I test the model in our video and the result is poor. Do you test the AP in voc dataset? Do you test the model in other video?

**Comment by unsky** [comment]
@chengshuai  how many iters? i get voc mAP78% without anyother tricks, i suggest 16W iters,and you need Adjust the learning rate  in training

**Comment by chengshuai** [comment]
@unsky 
I use the script from the your github, and  the parameter does not change. Can I get the same result from your model and script?

**Comment by chengshuai** [comment]
@unsky 
In file FP_Net_end2end.sh, could not find the file fpn_iter_25000.caffemodel, i repalce the model with VGG16 pretrain model  --weights data/imagenets/VGG16.v2.caffemodel

**Comment by chengshuai** [comment]
@unsky 

I train the FPN_caffe once again, the iters is 16w, and I change --weight from fpn_iter_25000.caffemodel(i am not have the caffemodel) to imagenets/VGG16.v2.caffemodel(VGG16 pretrain model) in FP_Net_end2end.sh. However, I get the mAP 61%, and I do not change the other code from https://github.com/unsky/FPN-caffe.

Could you give me some advice about the poor result? 

Thanks!

**Comment by chengshuai** [comment]
@unsky 

I train the FPN_caffe once again, the iters is 16w, and I change --weight from fpn_iter_25000.caffemodel(i am not have the caffemodel) to imagenets/VGG16.v2.caffemodel(VGG16 pretrain model) in FP_Net_end2end.sh. However, I get the mAP 61%, and I do not change the other code from https://github.com/unsky/FPN-caffe.

Could you give me some advice about the poor result? 

Thanks!

**Comment by unsky** [comment]
@chengshuai  draw the learning cure. and  choose a suit learning rate,  the models is not converge in the best

**Comment by chengshuai** [comment]
@unsky thank you for advice!
but I spend expensive time on training, could you share your script about the hyper parameters on voc?
And, if i change the datasets,such as coco or our datasets, should the hyper parameters change as well?

**Comment by junjieAI** [comment]
@chengshuai I got some problem when I use the same script to train my own data, hope you give me some suggestions or it is appreciated that tell me the way you did.

when I run ./experiments/scripts/FP_Net_end2end.sh, I got a problem as follow:
Traceback (most recent call last):
File "./tools/train_net.py", line 112, in
max_iters=args.max_iters)
File "/home/qi/Desktop/FPN-caffe-master/tools/../lib/fast_rcnn/train.py", line 157, in train_net
pretrained_model=pretrained_model)
File "/home/qi/Desktop/FPN-caffe-master/tools/../lib/fast_rcnn/train.py", line 43, in init
self.solver = caffe.SGDSolver(solver_prototxt)
File "/home/qi/Desktop/FPN-caffe-master/tools/../lib/roi_data_layer/layer.py", line 125, in setup
top[idx].reshape(1, self._num_classes * 4)
IndexError: Index out of range
And the pretrained_model I used is VGG16.v2.caffemodel, hope you can give me some help, Thanks

**Comment by chengshuai** [comment]
@junjieAI 

Check your script, maybe your train script have the space line.

**Comment by junjieAI** [comment]
@chengshuai 
I really appreciate your assistance, but I can't find the space line you said in the script, and for the “./FPN-caffe-master/models/pascal_voc/VGG16/FP_Net_end2end/train.prototxt" I just changed the "num_classes" to 11 and the corresponding "bbox_pred num_output" to 44. I do not change the other code from https://github.com/unsky/FPN-caffe.
How do you complete the training? Could you give me the instruction？ Thank you！

**Comment by unsky** [comment]
i have update codes

**Comment by lixiangamy** [comment]
cls_score_concat ：Top shape:4 21（12）？
error：Creating layer loss_cls
F0118 13:55:03.960583 15560 loss_layer.cpp:19] Check failed: bottom[0]->num() == bottom[1]->num() (4 vs. 1) The data and label should have the same number.
