### ISSUE TITLE
Some questions about your FPN

### ISSUE THREAD

**Issue by zhanglonghao1992** [unsky/FPN-caffe#11]
1.According to the paper，each rpn should have 3 different anchors（1 erea * 3 aspect ratios) because each levle has their own erea. But you still set 9 anchors （3 erea * 3 aspect ratios）at each level of rpn

2.Have you tried to share rpn weights and bias? It will save time and memory, and might improve the result

**Comment by unsky** [comment]
@zhanglonghao1992  
1. the anchor scale and ratios in the paper is suit for coco, we can design it  in our datasets. this set will effect the performance, so you can analyze the scale of  object in the images,and give an suit setting.
2. share weight and bias have try in my mxnet version.and i find it need more time to train,  and  it has little effect in voc dataset.

**Comment by zhanglonghao1992** [comment]
@unsky  3q~
