### ISSUE TITLE
一个训练的问题

### ISSUE THREAD

**Issue by DeanDon** [unsky/FPN-caffe#12]
训练的时候遇到了这个问题：
/home/AISSD/FPN-caffe/tools/../lib/rpn/anchor_target_layer.py:105: RuntimeWarning: invalid value encountered in sqrt
  k = np.floor(k0 + np.log2(np.sqrt(areas)*1.0 / 64))
Traceback (most recent call last):
  File "./tools/train_net.py", line 112, in <module>
    max_iters=args.max_iters)
  File "/home/AISSD/FPN-caffe/tools/../lib/fast_rcnn/train.py", line 162, in train_net
    model_paths = sw.train_model(max_iters)
  File "/home/AISSD/FPN-caffe/tools/../lib/fast_rcnn/train.py", line 101, in train_model
    self.solver.step(1)
  File "/home/AISSD/FPN-caffe/tools/../lib/rpn/anchor_target_layer.py", line 117, in forward
    if int(item)==p:
ValueError: cannot convert float NaN to integer
输出了一下这个anchor_target_layer.py中的
ws = gt_boxes[:, 2] - gt_boxes[:, 0]
            hs = gt_boxes[:, 3] - gt_boxes[:, 1]
            areas = ws * hs
            #print "debug::",ws,hs
            k = np.floor(k0 + np.log2(np.sqrt(areas)*1.0 / 64))
发现hs是负的，然后输出了一下gt_boxes的值：
DEBUG:: [[  5.97701132e-01   3.91703438e+04   5.20000000e+02   2.70160919e+02   1.00000000e+00]]
但是同样的数据在faster-rcnn中运行没有这个错，请问有谁知道这个问题怎么回事吗？

**Comment by unsky** [comment]
如果你在voc的数据集上训练，使用0.001左右的数据集是不会出现这种情况的，如果在别的数据集，你应该观察学习曲线找到一个合适的学习率，这个错误一般只有在box损失出现发散的时候出现，如果不是这个造成的还有一个可能，数据集以pascal voc 1-center为基准，如果你的数据集标准是以0-center为基准的话需要注释掉数据准备的-1部分，你自己debug下吧

**Comment by DeanDon** [comment]
@unsky 谢谢大神解答，我再调一下。
顺便问一下，如果要把前置网络换成resnet是不是只需要在prototxt里面将newC层的bottom换成resnet的对应特征图就可以了？

**Comment by unsky** [comment]
是的，前置网络可以换成任意一种网络结构

**Comment by DeanDon** [comment]
@unsky 谢谢。

**Comment by DeanDon** [comment]
@unsky 问题解决了，确实是pascal_voc imdb生成时坐标-1的问题。谢谢了。

**Comment by hmjbuaa** [comment]
请问这个问题修改了代码里哪个部分？

**Comment by DeanDon** [comment]
@hmjbuaa 
就是生成pascal voc数据库时
          ` x1 = float(bbox.find('xmin').text)-1
            y1 = float(bbox.find('ymin').text)-1
            x2 = float(bbox.find('xmax').text)-1
            y2 = float(bbox.find('ymax').text)-1`
去掉-1就好了

**Comment by hmjbuaa** [comment]
谢谢。我这样试过了，但是在迭代到120次的时候有个y1是11999，感觉原本应该是个负数

**Comment by lemon923** [comment]
我在cityscape数据集上训练rpn分支，总是出现梯度爆炸，请问有人遇到过这种现象吗？调小学习率可以训练，但是测试性能不是很好。
