### ISSUE TITLE
label and rois->num()  not equal. 

### ISSUE THREAD

**Issue by Aveirof7** [unsky/FPN-caffe#4]
I1103 18:47:46.824345   300 layer_factory.hpp:77] Creating layer loss_cls
F1103 18:47:46.824635   300 loss_layer.cpp:19] Check failed: bottom[0]->num() == bottom[1]->num() (4 vs. 1) The data and label should have the same number.

In your train.prototxt, after roi-data layer, you concat(axis=0) 4 roi_pool, then the num is 4, but the label num is 1, how to solve it?
I run it on my caffe, with your whole rpn files.
 THANKS!!

**Comment by Aveirof7** [comment]
@unsky

**Comment by unsky** [comment]
@Aveirof7  i have revised the source of caffe, you must compile the FPN-CAFFE

**Comment by Aveirof7** [comment]
@unsky  ok..but i canot compile it，the error is 'undefined sumbol:PyFPE_jbuf'
i creat it an conda env to compile it, but i cant solve the problem.
so, do you konw how to fix it?
and if not, can I concat 4labels,and make it num equal?
THANKS!

**Comment by unsky** [comment]
@Aveirof7  use cmake 

mkdir build
cd build
cmake ..
make -j16 all

**Comment by unsky** [comment]
what your mean? the files lib/pycocotools/ lib is not contain caffe, they are the dependent of the boxes program,
1. compile FPN-CAFFE
2. compile lib
if you have the error in 2.
delete all *.so files in the lib files  and recompile it

**Comment by Aveirof7** [comment]
@unsky  I fixed it, THX！!！
and it runs, using about 11G memery, with min_size800，max1000，a little too big

**Comment by Aveirof7** [comment]
@unsky 
I used your compiled caffe to replace my caffe, then it runs.
but it has some warning, 
**RuntimeWarning: overflow encountered in multiply**
Does it matter? and it trains so slow

**Comment by unsky** [comment]
@Aveirof7  the reason of RuntimeWarning  is occurred in the early stage because of the random state of the network ,  in generally it will disapper in two iter..

**Comment by unsky** [comment]
@Aveirof7  about the speed, there have many param you can have a try,like : batch size, image_size etc..

**Comment by Aveirof7** [comment]
@unsky THX!
I'll try it tomorrow
thank you!

**Comment by LIN-xr** [comment]
How did you solve this problem ? can you the detailed information ?
