### ISSUE TITLE
self._allowed_border = layer_params.get('allowed_border', 1000)

### ISSUE THREAD

**Issue by unicoe** [unsky/FPN-caffe#88]
FPN/lib/rpn/anchor_target_layer.py 中

self._allowed_border = layer_params.get('allowed_border', 1000)

请问为什么边界值要设为1000呢?如果设置为1000的话,在筛选anchor的时候,不就会把超过边界的anchor也包含进来?

**Comment by unsky** [comment]
原始论文里面支持框超出图片的部分，在这里因为是gt，所以不会出现框完全在图片外的情况

**Comment by unicoe** [comment]
明白了,感谢~
